# Github introduction

##

make a diagram where git at the center and arrows out to different places gitlab, github, bitbucket personal server, even the same comoputer but different "bare" folder (this isnt "safe" nor accessible by others, but totaly possible)

briefly talk about github things like PR, gitissues, staring and watching projects, collaborators and update dates/commits as a proxy of how active the project is. also do check which files typically being changed. Also mention the fact that it is very explicit when the project was started (initiated) how much work has gone into it (commits history) and roughly time frame and intervals of work


mention at some point README file as a general means of "silent"  communication then README.md and index.html as "special" files. README.md is the front page - apperance for your project. One can have multiple README.md files in subdirectories if necessary.


in simple workflow and collaborations git merge will work just fine. git will happy merge two different branches i.e all files in one location with all files in the other location if no two file conflict
