# Part IV: Static, multipaged website with rmarkdown and bookdown

Thus far we have been doing one to one mapping, from single Rmarkdown file to a single HTML file,
from a single Rmarkdow approach is very similar generating multi pages website)

introduce two new, must files
 index.Rmd
_site.yml
don't show navbar at the start, just three pages, index, aboutme and "blog entry"
explain website build via build tab/ button as oppose knit button (maybe need to confiigure the project?)
name: my_site and output_dir: website
check to see if you can do without navbar? maybe not, not a big deal if cant
reiterate output html_document or html_document2 both will work
this is the site generating function, site: rmarkdown::default_site or site: bookdown::bookdown_site

# Bookdown

All `.Rmd` files located in the same directory will be compiled into the book in the (alphabetical?) order.

- files that start with an underscore are skipped
- if there is an `index.Rmd` it will always be treated as a first file
- those settings can be overwritten via `_bookdown.yml`
- `_bookdown.yml` must co-exist with `.Rmd` files in the "book" directory

Bookdown has extended markdown even further for math https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#tab:theorem-envs

## work in progress

Besides these html_document() options,

gitbook() has three other arguments:

- `split_by` argument specifies how you want to split the HTML output into multiple pages

    - `rmd`: use the base filenames of the input Rmd files to create the HTML filenames, e.g., generate chapter3.html for chapter3.Rmd.
    - `none`: do not split the HTML file (the book will be a single HTML file).
    - `chapter`: split the file by the first-level headers.
    - `section`: split the file by the second-level headers.
    - `chapter+number` and `section+number`: similar to chapter and section, but the files will be numbered.

- `split_bib`
- `config`

- `collapse`
    - `section`
    - `subsection`

      scroll_highlight: yes
      before: null


## Cross-references

A normal paragraph.

(ref:foo) A scatterplot of the data `cars` using **base** R graphics.

```{r fig.cap='(ref:foo)'}
plot(cars)  # a scatterplot
```

## check

need to address difference between `html_document2` vs `gitbook`

https://bookdown.org/yihui/rmarkdown/bookdown-output.html#bookdown-output
