
# Git introduction

> When you are rock climbing you want to set your anchors often
> How often will depend on your experience and desire not to fall
> Git commit like you are vertically hanging off 70 feet rock

I am going to break to you right at the start that (unfortunately) doing git and GitHub is like rock climbing, but nonetheless it has great benefits for your research and analysis including making it more visible, reproducible and potentially very collaborative.

## Git explained

- [presentation](presentations/git/pres.html)

[Git](https://git-scm.com/doc) is one of many tools, but it is very popular. Git was designed for **tracking versions** of software development - a.k.a version control tool. While it hasn't been strictly design with scientific research projects in mind we will happily re-purpose git to help us stay on top of our research projects. In the git world everything rotates around a git repository, which is a "special" folder. Inside that folder every file and folder is "tracked" for changes. Git repositories often are synonymous with project folder. In our case the RStudio project folder will be the same as the git folder. In other words we are going to tack all changes in our project.

## Git demo

I am going to run through a live dome and than we are going to attempt do some of that ourself

- use example of "sorted" root project directory and now lets initiate this directory to be tracked by git using `git init` command in terminal (remember about README.md file)
- upload "sorted" directory to google Team drive, note the difference is that a single directory `.git` was added - that is all !
- now initialise `.Rproj` in the same directory via RStudio on personal computer and upload another copy to google team drive and observe the difference
<!--- ask students to download a copy of "sorted" directory for personal record -->

## Git clients a.k.a graphical user interface

Most of the time graphical user interface is shorten to GUI. Some command line tools, like git can have an additional "layer" on top of the "core" that simplifies the interface with the tool for end users. It is rather typical, at least in Unix/Linux (MacOS?) to have most applications (tools) to be accessible via command line and git is no exception. However command line interface an be a barrier for using the tools and doing work, hence why a more user friendly (arguably) graphical interface.

- [comprehensive list of git clients](https://git-scm.com/downloads/guis/)

RStudio also can act as a client to git an has some limited capabilities to use git for tracking. RStudio won't do everything that we need and this is why we need to do a tiny bit of command line in order to fully appreciate git.

## The first few git commands

- `git init` need to run it one off for every new (git) project. Most of the time this step is masked by git clients, and always forgotten
- `git status` show the work in progress
- `git log` show our commit history
- `git add`  "marking" the file that you are interested in saving (committing)
- `git commit` actually saving (committing) the file for permanent record

Let's work through very first git workflow, do

- open terminal tab
- git status
- git init
- git status
- git add project.Rproj
- git status
- git commit -m "first commit"
- git status
## running notes

- webpage from where I'll be copying text to commit
- talk about which files to commit/.gitignore https://git-scm.com/about


